variables:
  REPO_NAME: gitlab.rebrainme.com/devops_users_repos/2735/do-final
  APP: gitea
  VERSION: $CI_COMMIT_SHORT_SHA

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin

stages:
  - linting
  - build
  - deploy

go-lint:
  tags:
    - deploy
  stage: linting
  script:
    - cd $CI_PROJECT_DIR
    - golangci-lint run --disable-all -E errcheck 
  only:
      refs:
       - master
  

compile:
  tags:
    - deploy
  stage: build
  script:
    - TAGS="bindata" make build
  artifacts:
    paths:
      - $CI_PROJECT_DIR/$APP
  only:
      refs:
       - master


deployapp:
  tags:
    - deploy
  stage: deploy
  script:
    - mkdir -p /opt/$APP/versions/$VERSION
    - cp $CI_PROJECT_DIR/$APP /opt/$APP/versions/$VERSION
    - ln -s /opt/$APP/versions/$VERSION /opt/$APP/$APP 
  only:
      refs:
       - master