- name: Create version dir
  file:
    path: "{{ app_version_dir }}/{{ app_version }}"
    state: directory
    mode: 0755
  remote_user: "{{ deploy_user }}"

- name: Copy bin to version dir
  copy:
    dest: "{{ app_version_dir }}/{{ app_version }}"
    src: "{{ app_build_dir }}/{{ app_name }}"
    remote_src: yes
    mode: 0755
  remote_user: "{{ deploy_user }}"

- name: Create symlink
  file:
    path: "{{ app_deploy_dir }}/{{ app_name }}"
    src: "{{ app_version_dir }}/{{ app_version }}/{{ app_name }}"
    state: link
    mode: 0755
  remote_user: "{{ deploy_user }}"

- name: Database migration
  shell: "{{ app_deploy_dir }}/{{ app_name }} migrate --config {{ app_conf_dir }}/app.ini"
  environment:
    GITEA_WORK_DIR: "{{ app_work_dir }}"
  remote_user: "{{ app_user }}"
  when: db_created.changed
