---
- name: Create service file
  template:
    src: "{{ app_service_name }}.j2"
    dest: "/etc/systemd/system/{{ app_service_name }}"
  notify: start service

- name: Allow service control to deploy user
  community.general.sudoers:
    name: "{{ app_name }}"
    user: "{{ deploy_user }}"
    commands:
      - "/bin/systemctl start {{ app_service_name }}"
      - "/bin/systemctl stop {{ app_service_name }}"
      - "/bin/systemctl restart {{ app_service_name }}"
      - "/bin/systemctl reload {{ app_service_name }}"
    nopassword: true
