---

- hosts: all
  become: yes
  roles:
    - role: iptables
    - role: admin-users
    - role: node-exporter
    - role: fluentd
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml

- hosts: lb
  become: yes
  remote_user: ubuntu
  roles:
    - role: nginx
    - role: letsencrypt
    - role: nginxlog-exporter
    - role: nginx-lb
      vars:
#        host_filename: http

- hosts: app
  become: yes
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml
  roles:
    - role: deploy-users
    - role: go
    - role: nodejs
    - role: psql
    - role: app-deploy
      become: no
    - role: gitlab-runner

- hosts: log
  become: yes
  roles:
    - role: elasticsearch
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml

- hosts: prom
  become: yes
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml
  roles:
    - role: prometheus
    - role: grafana
      vars:
        grafana_protocol: http
