---

- hosts: all
  become: yes
  roles:
    - role: admin-users
    - role: node-exporter
    - role: fluentd
    - role: iptables
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml

- hosts: app
  become: yes
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml
  roles:
    - role: deploy-users
    - role: go
    - role: nodejs
    - role: nginx
    - role: letsencrypt
    - role: nginxlog-exporter
    - role: psql
    - role: app-deploy
      become: no
    - role: nginx-upstream
#      vars:
#        host_filename: http
    - role: gitlab-runner

- hosts: log
  become: yes
  roles:
    - role: elasticsearch
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml

- hosts: prom
  become: yes
  remote_user: ubuntu
  vars_files:
    - vaults/vault.yml
  roles:
    - role: prometheus
    - role: nginx
    - role: letsencrypt
    - role: nginxlog-exporter
    - role: nginx-upstream
      vars:
        app_name: grafana
        app_port: 3000
#        host_filename: http
    - role: grafana
#      vars:
#        grafana_protocol: http
