- name: create prometheus datasource
  community.grafana.grafana_datasource:
    name: prometheus
    grafana_url: "{{ grafana_protocol }}://{{ inventory_hostname }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    ds_type: prometheus
    ds_url: "http://{{ ansible_facts['eth0']['ipv4']['address'] }}:9090"
    access: proxy

- name: Create elasticsearch datasource
  community.grafana.grafana_datasource:
    name: "datasource-elastic"
    grafana_url: "{{ grafana_protocol }}://{{ inventory_hostname }}"
    grafana_user: "admin"
    grafana_password: "{{ grafana_admin_password }}"
    org_id: "1"
    ds_type: "elasticsearch"
    ds_url: "http://{{ hostvars[item]['ansible_facts']['eth0']['ipv4']['address'] }}:9200"
    database: "logs-*"
    time_field: "@timestamp"
    time_interval: "1m"
    es_version: 70
    max_concurrent_shard_requests: 42
  loop: "{{ groups['log'] }}"
