---
- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Add elasticsearch mirror
  copy:
    src: elastic-7.x.list
    dest: "/etc/apt/sources.list.d/elastic-7.x.list"

- name: Install elasticsearch
  apt:
    name: elasticsearch
    state: present
    update_cache: yes
