---

- name: Get gitlab-runner binary
  get_url:
    url: '{{ gitlab_runner_url }}'
    dest: '/usr/local/bin/gitlab-runner'
    mode: a+x

- name: Install gitlab-runner
  command: 'gitlab-runner install --user={{ deploy_user }} --working-directory={{ app_build_dir }}'

- name: Start gitlab-runner service
  command: 'gitlab-runner start'

- name: Register runner to GitLab
  command: 'gitlab-runner register --url https://gitlab.rebrainme.com/ --registration-token {{ gitlab_runner_registration_token }} --tag-list "deploy" --executor "shell" --non-interactive'
