---

- name: Install gitlab-runner
  apt:
    allow_unauthenticated: yes
    name: gitlab-runner
    state: present
    update_cache: yes
  notify: start gitlab-runner

- name: Add deploy user to gitlab group
  user:
    name: '{{ deploy_user }}'
    groups: gitlab-runner
    append: yes

- name: Modify service file
  template:
    src: gitlab-runner.service.j2
    dest: "/lib/systemd/system/gitlab-runner.service"
  notify: restart gitlab-runner

- name: Register runner to GitLab
  command: 'gitlab-runner register --url https://gitlab.rebrainme.com/ --registration-token {{ gitlab_runner_registration_token }} --tag-list "deploy" --executor "shell" --non-interactive'
