---

- name: Install gitlab-runner
  apt:
    allow_unauthenticated: yes
    name: gitlab-runner
    state: present
    update_cache: yes
  notify: start gitlab-runner

- name: Modify service file
  copy:
    src: gitlab-ci-multi-runner.service
    dest: "/etc/systemd/system/gitlab-ci-multi-runner.service"
  notify: restart gitlab-runner

- name: Register runner to GitLab
  command: 'gitlab-runner register --url https://gitlab.rebrainme.com/ --registration-token {{ gitlab_runner_registration_token }} --tag-list "deploy" --executor "shell" --non-interactive'
